a=int(input("enter the total buget:"))
b=int(input("enter the total markating ratio:"))
c=int(input("enter the total developing ratio:"))
d=int(input("enter the total operation:"))
e = a * (b / 10)
f = a * (c / 10)
g = a * (d / 10)
print ("markating buget:",e)
print ("developing ratio:",f)
print ("operation:",g)